require:
  - rubocop-flexport

AllCops:
  NewCops: enable

Style/FrozenStringLiteralComment:
  Enabled: false

Style/MutableConstant:
  Enabled: false

Style/GlobalStdStream:
  Enabled: false

Style/NumericPredicate:
  Enabled: false

Gemspec/RequiredRubyVersion:
  Enabled: false

Style/Documentation:
  Enabled: false
